size_t strlen_(const char *s);
char *strcpy_(char *s1, const char *s2);
char *strchr_(const char *s1, int ch);
char *strrchr_(const char *s, int ch);
char *strcat_(char *s1, const char *s2);
int strcmp_ (const char *s1, const char *s2);
size_t strspn_ (const char *s1, const char *s2);
size_t strcspn_ (const char *s1, const char *s2);
char *strstr_(const char *s1, const char *s2);
char *strtok_r_ (char *str, const char *delim, char **saveptr);
